version: '3.7'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - wpsite
  
  phpmyadmin:
    image: phpmyadmin:5.0.4-apache
    depends_on:
      - db
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=admin 
    networks:
      - wpsite
  
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - 8080:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=admin
      - WORDPRESS_DB_PASSWORD=admin
    volumes: 
      - ./site:/var/www/html
    networks:
      - wpsite

networks:
  wpsite:
volumes:
  db_data:
